print("isalnum")
print("Hello","Hello".isalnum())
print("He o","He o".isalnum())
print('isalpha')
print("Hello","Hello".isalpha())
print("He123","he123".isalpha())
print('isnumeric')
print("12345","12345".isnumeric())
print("He123","He123".isnumeric())